In [2]:
print("hello")

hello


In [3]:
print("how are you")


how are you


In [4]:
import numpy as np

# Basic Array Creation

## np.array()
**Purpose**: Creates a NumPy array from a Python list or nested lists.
**Use Case**: Convert regular Python lists into efficient NumPy arrays for mathematical operations.
**Key Features**:
- Converts Python lists to NumPy arrays
- Supports multi-dimensional arrays
- More memory efficient than Python lists
- Enables vectorized operations

**Example**: `np.array([1, 2, 3, 4, 5])` creates a 1D array
**Example**: `np.array([[1,2,3],[4,5,6]])` creates a 2D array

In [5]:
ARR = np.array([1, 2, 3, 4, 5])
print(ARR)

[1 2 3 4 5]


In [6]:
a = [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

In [7]:
l =[[1,2,3],[4,5,6],[7,8,9]]
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Functions

## np.arange()
**Purpose**: Creates an array with evenly spaced values within a given interval.
**Use Case**: Generate sequences of numbers, similar to Python's range() but returns an array.
**Syntax**: `np.arange(start, stop, step)`
**Example**: `np.arange(10)` creates [0,1,2,3,4,5,6,7,8,9]

## np.zeros()
**Purpose**: Creates an array filled with zeros.
**Use Case**: Initialize arrays with a default value of zero, useful for pre-allocation.
**Syntax**: `np.zeros((rows, columns))`
**Example**: `np.zeros((4,8))` creates a 4x8 array of zeros

## np.ones()
**Purpose**: Creates an array filled with ones.
**Use Case**: Initialize arrays with a default value of one, useful for calculations.
**Syntax**: `np.ones((rows, columns))`
**Example**: `np.ones((2,3))` creates a 2x3 array of ones

## np.linspace()
**Purpose**: Creates an array with evenly spaced numbers over a specified interval.
**Use Case**: Generate specific number of points between two values (useful for plotting).
**Syntax**: `np.linspace(start, stop, num_points)`
**Example**: `np.linspace(1,10,3)` creates [1.0, 5.5, 10.0] - 3 equal parts between 1 and 10

In [9]:
arr1 = np.arange(10)
print(arr1)


[0 1 2 3 4 5 6 7 8 9]


In [10]:
arr=np.zeros((4,8)) #4 are rows and 8 are columns
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr=np.linspace(1,10,3) #linspace is called linear space which makes 3 equal parts between 1 and 10 here
print(arr)

[ 1.   5.5 10. ]


# Random Generation Functions

## np.random.rand()
**Purpose**: Creates an array with random values from a uniform distribution between 0 and 1.
**Use Case**: Generate random numbers for simulations, testing, or initialization.
**Syntax**: `np.random.rand(d1, d2, ..., dn)`
**Example**: `np.random.rand(5)` creates 5 random numbers between 0 and 1

## np.random.randn()
**Purpose**: Creates an array with random values from a standard normal distribution (mean=0, std=1).
**Use Case**: Generate normally distributed random numbers for statistical simulations.
**Syntax**: `np.random.randn(d1, d2, ..., dn)`
**Example**: `np.random.randn(10)` creates 10 random numbers from normal distribution

## np.random.randint()
**Purpose**: Creates an array with random integers between specified values.
**Use Case**: Generate random integers for random sampling, testing, or games.
**Syntax**: `np.random.randint(low, high, size)`
**Example**: `np.random.randint(10,20,10)` creates 10 random integers between 10 and 19

In [13]:
np.random.rand(5)

array([0.28466445, 0.10161563, 0.90150061, 0.1449817 , 0.53524468])

In [14]:
np.random.randn(10)

array([-0.44290795, -0.5645732 , -0.65784558,  0.04438543,  1.1964697 ,
        0.71325673,  0.06973322, -0.15065853, -0.25788263, -0.52801091])

In [15]:
np.random.randint(10,20,10)

array([17, 15, 19, 16, 10, 18, 16, 17, 11, 16])

# Array Attributes

## arr.shape
**Purpose**: Returns the dimensions of the array as a tuple.
**Use Case**: Check the size and structure of your array.
**Example**: `arr.shape` returns (3, 3) for a 3x3 array

## arr.size
**Purpose**: Returns the total number of elements in the array.
**Use Case**: Count how many values are stored in the array.
**Example**: `arr.size` returns 9 for a 3x3 array (3 × 3 = 9)

## arr.dtype
**Purpose**: Returns the data type of elements in the array.
**Use Case**: Check what type of data is stored (int64, float64, etc.).
**Example**: `arr.dtype` returns dtype('int64') for integer arrays

In [16]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.shape

(3, 3)

In [18]:
arr.size

9

In [19]:
arr.dtype

dtype('int64')

# Array Methods

## arr.min()
**Purpose**: Returns the minimum value in the array.
**Use Case**: Find the smallest element in your data.
**Example**: `arr.min()` returns 1 for array [[1,2,3],[4,5,6],[7,8,9]]

## arr.max()
**Purpose**: Returns the maximum value in the array.
**Use Case**: Find the largest element in your data.
**Example**: `arr.max()` returns 9 for array [[1,2,3],[4,5,6],[7,8,9]]

## arr.sum()
**Purpose**: Returns the sum of all elements in the array.
**Use Case**: Calculate total of all values.
**Example**: `arr.sum()` returns 45 for array [[1,2,3],[4,5,6],[7,8,9]]

## np.sum(arr, axis=1)
**Purpose**: Returns the sum along a specific axis.
**Use Case**: Calculate row-wise (axis=1) or column-wise (axis=0) sums.
**Example**: `np.sum(arr, axis=1)` returns [6, 15, 24] for row sums

## arr.mean()
**Purpose**: Returns the average value of all elements.
**Use Case**: Calculate the arithmetic mean of your data.
**Example**: `arr.mean()` returns 5.0 for array [[1,2,3],[4,5,6],[7,8,9]]

## arr.std()
**Purpose**: Returns the standard deviation of elements.
**Use Case**: Measure the spread or dispersion of your data.
**Example**: `arr.std()` returns 2.58 for array [[1,2,3],[4,5,6],[7,8,9]]

## arr.argmax()
**Purpose**: Returns the index of the maximum value.
**Use Case**: Find the position of the largest element.
**Example**: `arr.argmax()` returns 8 (index of value 9) for array [[1,2,3],[4,5,6],[7,8,9]]

## arr.argmin()
**Purpose**: Returns the index of the minimum value.
**Use Case**: Find the position of the smallest element.
**Example**: `arr.argmin()` returns 0 (index of value 1) for array [[1,2,3],[4,5,6],[7,8,9]]

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.min()

np.int64(1)

In [22]:
arr.max()

np.int64(9)

In [23]:
arr.sum()

np.int64(45)

In [24]:
np.sum(arr,axis=1) #sum of each row

array([ 6, 15, 24])

In [25]:
arr.mean()

np.float64(5.0)

In [26]:
arr.std()

np.float64(2.581988897471611)

In [27]:
arr.argmax()

np.int64(8)

In [28]:
arr.argmin()

np.int64(0)

# Reshaping and Resizing

## arr.reshape()
**Purpose**: Changes the shape of an array without changing its data.
**Use Case**: Reorganize data into different dimensions for analysis or processing.
**Syntax**: `arr.reshape(rows, columns)`
**Key Features**:
- Total elements must remain the same
- Returns a new view of the data (doesn't copy unless necessary)
- Can use -1 to automatically calculate one dimension

**Example**: `arr.reshape(5,6)` converts a 30-element 1D array into a 5x6 2D array
**Example**: `arr.reshape(-1, 6)` automatically calculates rows for 6 columns

In [29]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [30]:
arr.reshape(5, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [31]:
arr= arr.reshape(5,6)

In [32]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

# Array Indexing

Array indexing in NumPy allows you to access and modify specific elements or portions of arrays. NumPy provides powerful indexing capabilities that are more flexible than Python lists.

## Types of Indexing:
1. **Basic Indexing** - Access individual elements
2. **Slicing** - Access ranges of elements  
3. **Boolean Indexing** - Access elements based on conditions
4. **Fancy Indexing** - Access elements using integer arrays

## Numpy Indexing and Slicing Vectors (1D Arrays)

### Basic Indexing
**Purpose**: Access individual elements using their position.
**Syntax**: `arr[index]`
**Use Case**: Get or modify specific elements in a 1D array.
**Note**: Indexing starts from 0 (first element) and supports negative indexing (-1 for last element).

### Slicing
**Purpose**: Access a range of elements using start:stop:step notation.
**Syntax**: `arr[start:stop:step]`
**Key Features**:
- **start**: Starting index (inclusive)
- **stop**: Ending index (exclusive)
- **step**: Step size (optional, defaults to 1)
- Omitting start/step uses defaults (0 for start, 1 for step)
- Negative step works for reverse slicing

**Examples**:
- `arr[1:5]` → Elements from index 1 to 4
- `arr[:3]` → First 3 elements
- `arr[2:]` → Elements from index 2 to end
- `arr[::2]` → Every second element
- `arr[::-1]` → Reverse the array

In [34]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[1:5] #slicing

array([12, 13, 14, 15])

## Numpy Indexing and Slicing of Matrix (2D Arrays)

### Basic Matrix Indexing
**Purpose**: Access individual elements using row and column positions.
**Syntax**: `arr[row_index, column_index]`
**Use Case**: Get or modify specific elements in a 2D array.
**Example**: `arr[0,1]` → Element at first row, second column

### Matrix Slicing
**Purpose**: Access submatrices or portions of the 2D array.
**Syntax**: `arr[row_start:row_stop, col_start:col_stop]`
**Key Features**:
- First part controls rows, second part controls columns
- Each part follows the same start:stop:step pattern as 1D arrays
- Can mix specific indices with slicing

### Common Slicing Patterns:
- `arr[0:2, 1:3]` → Rows 0-1, Columns 1-2 (2×2 submatrix)
- `arr[3:6, 3:5]` → Rows 3-5, Columns 3-4 (3×2 submatrix)
- `arr[:, 2]` → All rows, column 2 (entire column)
- `arr[1, :]` → Row 1, all columns (entire row)
- `arr[::2, ::2]` → Every second row and column

**Use Cases**:
- Extracting regions of interest from images
- Selecting specific data columns from datasets
- Creating submatrices for mathematical operations

In [39]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [42]:
arr[0,1]

np.int64(2)

In [44]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [52]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [54]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

## Boolean Indexing

### Purpose
**Purpose**: Select elements from an array based on conditions, returning elements that satisfy the condition.
**Use Case**: Filter data based on criteria, find elements that meet specific conditions.

### How It Works
1. **Create Boolean Mask**: Apply a condition to the array → returns boolean array (True/False)
2. **Apply Mask**: Use the boolean array to index the original array → returns only True elements

### Syntax
```python
# Step 1: Create boolean mask
mask = arr > value
# Step 2: Apply mask
filtered_arr = arr[mask]

# Or in one line:
filtered_arr = arr[arr > value]
```

### Common Conditions
- `arr > 5` → Elements greater than 5
- `arr < 10` → Elements less than 10
- `arr == 3` → Elements equal to 3
- `arr != 0` → Elements not equal to 0
- `arr % 2 == 0` → Even numbers
- `arr >= 10` & `arr <= 20` → Elements between 10 and 20

### Key Features
- Returns a **new array** with only the elements that meet the condition
- The resulting array is **1D** regardless of the original array shape
- Can combine multiple conditions using `&` (and) or `|` (or)
- Much faster than manual looping for large arrays

**Example**: `arr[arr % 2 == 0]` returns all even numbers from the array

In [56]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [57]:
bool_index = arr % 2 == 0
print(bool_index)

[False  True False  True False  True False  True False  True]


In [58]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Array Operations

Array operations in NumPy allow you to perform mathematical computations efficiently on arrays. NumPy supports element-wise operations, broadcasting, and specialized matrix operations that are optimized for performance.

## Types of Array Operations:
1. **Arithmetic Operations** - Element-wise mathematical operations
2. **Broadcasting** - Operations between arrays of different shapes
3. **Matrix Operations** - Linear algebra operations
4. **Array Manipulation** - Stacking, splitting, and reshaping
5. **Copy Operations** - Deep vs shallow copying

In [60]:
import numpy as np

### Arithmetic Operations

**Purpose**: Perform element-wise mathematical operations between arrays of the same size.
**Requirement**: Arrays must have the same shape to perform arithmetic operations.
**Use Case**: Mathematical computations on data, signal processing, statistical calculations.

## Supported Operations:
- **Addition (+)**: Element-wise sum of arrays
- **Subtraction (-)**: Element-wise difference between arrays
- **Multiplication (*)**: Element-wise product (not matrix multiplication)
- **Division (/)**: Element-wise division
- **Floor Division (//)**: Element-wise integer division
- **Exponentiation (**)**: Element-wise power operation

## Key Features:
- Operations are performed element by element
- Results in a new array with the same shape
- Much faster than Python loops for large arrays
- Supports all basic arithmetic operators

**Example**: `a1 + a2` adds corresponding elements: [1+6, 2+7, 3+8, 4+9, 5+10] = [7, 9, 11, 13, 15]

In [ ]:
a1 = np.array([1, 2, 3, 4, 5]) #The size of both array should be same to performa any operation
a2 = np.array([6, 7, 8, 9, 10])


array([1, 2, 3, 4, 5])

In [63]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [64]:
a1-a2

array([-5, -5, -5, -5, -5])

In [65]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [66]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [67]:
a1//a2

array([0, 0, 0, 0, 0])

In [68]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

### Broadcasting

**Purpose**: Perform arithmetic operations between arrays of different shapes by automatically expanding the smaller array.
**Use Case**: Apply scalar operations to arrays, combine arrays of different dimensions efficiently.

## How Broadcasting Works:
1. **Compare shapes** from right to left
2. **Expand dimensions** of size 1 to match larger array
3. **Repeat values** along expanded dimensions
4. **Perform operation** element-wise

## Broadcasting Rules:
- Dimensions must be compatible (same size or one is 1)
- Missing dimensions are padded with 1 on the left
- Size 1 dimensions are "stretched" to match larger sizes

## Common Examples:
- **Array + Scalar**: `arr + 10` adds 10 to every element
- **Matrix + Scalar**: `matrix + 5` adds 5 to every element
- **Vector + Matrix**: Automatically expands vector to match matrix dimensions

## Key Benefits:
- Eliminates need for explicit loops
- Memory efficient (doesn't actually copy data)
- Enables concise mathematical expressions
- Essential for scientific computing

**Example**: `arr2 + 10` adds 10 to each element of the 5×5 matrix

In [72]:
l=np.array([10,20,30,40,50])
l

array([10, 20, 30, 40, 50])

In [73]:
l + 10

array([20, 30, 40, 50, 60])

In [76]:
arr2 = np.arange(1, 26).reshape(5, 5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [77]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

### Deep and Shallow Copy

**Purpose**: Control how array data is copied to avoid unintended modifications.

## Shallow Copy (View)
**Purpose**: Create a new reference to the same data without copying.
**Syntax**: `new_array = original_array[ slicing ]` or `new_array = original_array.view()`
**Key Features**:
- No data is copied - just a new view of the same memory
- Changes to the view affect the original array
- Memory efficient
- Default behavior for slicing operations

## Deep Copy
**Purpose**: Create a completely independent copy of the array data.
**Syntax**: `new_array = original_array.copy()`
**Key Features**:
- Creates a complete copy of the data
- Changes to the copy don't affect the original
- Uses more memory
- Essential when you need independent arrays

## When to Use Each:
- **Shallow Copy**: When you need different views of the same data
- **Deep Copy**: When you need to modify data without affecting the original

## Key Concept:
NumPy slicing creates views by default for performance, but sometimes you need independent copies.

**Example**: `b = a.copy()` creates an independent array where changes to `b` don't affect `a`

In [105]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [106]:
slice = a[0:5]
print(slice)

[1 2 3 4 5]


In [107]:
slice * 10


array([10, 20, 30, 40, 50])

In [108]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [109]:
a[4:6]*10

array([50, 60])

In [110]:
a

b=a.copy()

In [111]:
a
b[0] = 99

In [112]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [113]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Matrix Operations

**Purpose**: Perform linear algebra operations on matrices (2D arrays).

## Element-wise vs Matrix Operations:
- **Element-wise (*)**: Multiplies corresponding elements
- **Matrix multiplication (@)**: Performs proper matrix multiplication

## Key Matrix Operations:

### Matrix Multiplication (Dot Product)
**Purpose**: Multiply matrices following linear algebra rules.
**Syntax**: `A @ B` or `np.dot(A, B)`
**Requirement**: Inner dimensions must match (A columns = B rows)
**Use Case**: Linear transformations, solving systems of equations, neural networks

### Transpose
**Purpose**: Flip matrix over its diagonal (rows become columns).
**Syntax**: `matrix.T` or `matrix.transpose()`
**Use Case**: Matrix operations, data transformation, preparing for multiplication

## Key Features:
- **@ operator**: Modern Python syntax for matrix multiplication
- **np.dot()**: Traditional function for matrix multiplication
- **.T attribute**: Quick way to transpose matrices
- Optimized for performance with BLAS libraries

## Example:
For 2×2 matrices A and B:
- `A * B` = [[1×5, 2×6], [3×7, 4×8]] = [[5, 12], [21, 32]] (element-wise)
- `A @ B` = [[1×5+2×7, 1×6+2×8], [3×5+4×7, 3×6+4×8]] = [[19, 22], [43, 50]] (matrix multiplication)

In [114]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [115]:
A

array([[1, 2],
       [3, 4]])

In [116]:
B

array([[5, 6],
       [7, 8]])

In [117]:
A * B

array([[ 5, 12],
       [21, 32]])

In [ ]:
#Dot Product 
A @ B

array([[19, 22],
       [43, 50]])

In [119]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [120]:
A.T

array([[1, 3],
       [2, 4]])

### Advanced Array Manipulation

**Purpose**: Combine, split, and reorganize arrays for complex data operations.

## Array Stacking Operations
**Purpose**: Join multiple arrays together to form larger arrays.

### Vertical Stack (vstack)
**Purpose**: Stack arrays vertically (row-wise).
**Syntax**: `np.vstack((array1, array2, ...))`
**Requirement**: Arrays must have the same number of columns
**Result**: New array with combined rows
**Use Case**: Combining datasets, building larger matrices from blocks

### Horizontal Stack (hstack)
**Purpose**: Stack arrays horizontally (column-wise).
**Syntax**: `np.hstack((array1, array2, ...))`
**Requirement**: Arrays must have the same number of rows
**Result**: New array with combined columns
**Use Case**: Adding features to datasets, combining side-by-side data

### Column Stack (column_stack)
**Purpose**: Stack 1D arrays as columns of a 2D array.
**Syntax**: `np.column_stack((array1, array2, ...))`
**Requirement**: Input arrays should be 1D
**Result**: 2D array with each input as a column
**Use Case**: Creating feature matrices from separate variables

## Array Splitting Operations
**Purpose**: Divide arrays into smaller sub-arrays.

### Horizontal Split (hsplit)
**Purpose**: Split array horizontally (column-wise).
**Syntax**: `np.hsplit(array, sections)`
**Result**: List of arrays split along columns
**Use Case**: Separating features, dividing data for parallel processing

### Vertical Split (vsplit)
**Purpose**: Split array vertically (row-wise).
**Syntax**: `np.vsplit(array, sections)`
**Result**: List of arrays split along rows
**Use Case**: Creating train/test splits, batch processing

## Key Features:
- All stacking operations return new arrays
- Splitting operations return lists of arrays
- Original arrays remain unchanged
- Essential for data preprocessing and organization

### Stacking Arrays

In [131]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [132]:
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [133]:
np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [135]:
np.column_stack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Splitting Arrays

In [137]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [138]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [139]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]